---
name: Continous integration of Stacky

on:
  pull_request:
    branches:
      - master
      - main
    types: [opened, synchronize, edited, ready_for_review]

jobs:

  ci:
    name: build and archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - id: build
        uses: OpenAstronomy/build-python-dist@v1
        with:
          pure_python_wheel: true
      - name: Persist build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stacky_draft_wheel
          path: |
            dist/*.whl
          retention-days: 2


  linter:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"

  typecheck:
    name: static type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - run: pip install asciitree ansicolors simple-term-menu mypy
      - run: mypy ./src/stacky/stacky.py

